name: 测试网站

on:
  pull_request:
    branches: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: |
        npm i -g hexo-cli
        npm i
        hexo generate
